name: Build Download Page (multi-folder)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate index.html at repo root
      # Pages serves from main /(root), so we write to "."
        shell: bash
        run: |
          OWNER="DAP2022"
          REPO="DataScienceTrainingCurriculum"
          BRANCH="main"

          SERVE_DIR="."   # keep this as "." since Pages serves from root
          OUT="$SERVE_DIR/index.html"

          mksection () {
            local title="$1"; shift
            echo "<h2>${title}</h2><ul>"
            while IFS= read -r -d '' f; do
              rel="${f#./}"                       # strip leading ./ for clean URL
              name="$(basename "$f")"
              raw="https://github.com/${OWNER}/${REPO}/raw/${BRANCH}/${rel}"
              echo -n "<li><a href=\"${rel}\" download>Download ${name}</a>"
              # For ipynb, also offer an “Open in Colab” convenience link
              if [[ "$name" == *.ipynb ]]; then
                colab="https://colab.research.google.com/github/${OWNER}/${REPO}/blob/${BRANCH}/${rel}"
                echo -n " &nbsp;|&nbsp; <a href=\"${colab}\">Open in Colab</a>"
              fi
              echo " &nbsp;|&nbsp; <a href=\"${raw}\">View raw on GitHub</a></li>"
            done < <(find "$@" -type f \( -name "*.ipynb" -o -name "*.Rmd" \) -print0 | sort -z)
            echo "</ul>"
          }

          {
            echo "<!doctype html><meta charset='utf-8'><title>Download Course Files</title>"
            echo "<h1>Download Course Files</h1>"
            mksection "Programming / Python I (.ipynb)" programming/pythoni/course_content_jupyter_notebooks || true
            mksection "Programming / Python II (.ipynb)" programming/pythonii/course_content_jupyter_notebooks || true
            mksection "Programming / R I (.rmd)" programming/ri || true
            mksection "Programming / R II (.rmd)" programming/rii || true
            echo "<p>Tip: If your browser ignores the download, use the “View raw on GitHub” link and save the file.</p>"
            echo "<p><a href=\"https://github.com/${OWNER}/${REPO}/archive/refs/heads/${BRANCH}.zip\">Download the entire repo as ZIP</a></p>"
          } > "$OUT"

      - name: Commit generated page
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-generate download index"
          file_pattern: index.html
