name: Build Section Download Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate per-section download pages
        shell: bash
        run: |
          OWNER="DAP2022"
          REPO="DataScienceTrainingCurriculum"
          BRANCH="main"

          # List of sections to generate (folder path | human title)
          sections=(
            "programming/pythoni|Programming in Python I"
            "programming/pythonii|Programming in Python II"
            "programming/ri|Programming in R I"
            "programming/rii|Programming in R II"
          )

          gen_section () {
            local dir="$1"
            local title="$2"
            local out="${dir%/}/index.html"
            mkdir -p "$dir"

            {
              echo "<!doctype html><meta charset='utf-8'><title>${title} — Downloads</title>"
              echo "<h1>${title} — Downloads</h1>"

              # Python notebooks in standard subfolder (if present)
              if [ -d "${dir}/course_content_jupyter_notebooks" ]; then
                echo "<h2>Jupyter Notebooks (.ipynb)</h2><ul>"
                while IFS= read -r -d '' f; do
                  rel="${f#./}"
                  name="$(basename "$f")"
                  raw="https://github.com/${OWNER}/${REPO}/raw/${BRANCH}/${rel}"
                  colab="https://colab.research.google.com/github/${OWNER}/${REPO}/blob/${BRANCH}/${rel}"
                  echo "<li><a href=\"/${rel}\" download>Download ${name}</a> &nbsp;|&nbsp; <a href=\"${colab}\">Open in Colab</a> &nbsp;|&nbsp; <a href=\"${raw}\">View raw</a></li>"
                done < <(find "${dir}/course_content_jupyter_notebooks" -type f -name "*.ipynb" -print0 | sort -z)
                echo "</ul>"
              fi

              # Any R Markdown files in the section tree
              if find "$dir" -type f -name "*.Rmd" | grep -q .; then
                echo "<h2>R Markdown (.Rmd)</h2><ul>"
                while IFS= read -r -d '' f; do
                  rel="${f#./}"
                  name="$(basename "$f")"
                  raw="https://github.com/${OWNER}/${REPO}/raw/${BRANCH}/${rel}"
                  echo "<li><a href=\"/${rel}\" download>Download ${name}</a> &nbsp;|&nbsp; <a href=\"${raw}\">View raw</a></li>"
                done < <(find "$dir" -type f -name "*.Rmd" -print0 | sort -z)
                echo "</ul>"
              fi

              echo "<p><a href=\"/\">← Back to Home</a></p>"
            } > "$out"
          }

          for entry in "${sections[@]}"; do
            IFS='|' read -r path title <<< "$entry"
            gen_section "$path" "$title"
          done

      - name: Commit generated pages
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-generate section download pages"
          file_pattern: programming/**/index.html

