name: Quarto Publish

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbclient nbformat nbconvert numpy pandas matplotlib seaborn

      - name: Execute notebooks
        run: |
          # Run each notebook in-place, update outputs
          find notebooks -name "*.ipynb" -print0 | \
          xargs -0 -I {} jupyter nbconvert \
            --to notebook \
            --inplace \
            --execute \
            --ExecutePreprocessor.timeout=600 {}

      - name: Render Quarto project
        uses: quarto-dev/quarto-actions/render@v2

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          publish_branch: gh-pages
